name: Go Lint and Check Style

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check Style
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
