name: Lint and test

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Add go to path
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Check style
        run: make check-style

      - name: Run tests
        run: make test
