name: Lint and test

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: Run tests # Changing job name breaks PR checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Lint code
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Run tests
        run: make test
